#import <DOM/EventTarget.idl>
#import <DOM/EventHandler.idl>
#import <MediaSourceExtensions/MediaSourceHandle.idl>
#import <MediaSourceExtensions/SourceBuffer.idl>
#import <MediaSourceExtensions/SourceBufferList.idl>

[Exposed=(Window,DedicatedWorker)]
interface MediaSource : EventTarget {
    constructor();

    readonly attribute SourceBufferList sourceBuffers;
    readonly attribute SourceBufferList activeSourceBuffers;
    readonly attribute ReadyState readyState;
    [Exposed=DedicatedWorker] readonly attribute MediaSourceHandle handle;
    static readonly attribute boolean canConstructInDedicatedWorker;

    attribute unrestricted double duration;

    attribute EventHandler onsourceopen;
    attribute EventHandler onsourceended;
    attribute EventHandler onsourceclose;

    SourceBuffer addSourceBuffer(DOMString type);
    undefined removeSourceBuffer(SourceBuffer sourceBuffer);
    undefined endOfStream(optional EndOfStreamError error);
    undefined setLiveSeekableRange(double start, double end);
    undefined clearLiveSeekableRange();

    static boolean isTypeSupported(DOMString type);
};

enum ReadyState { "closed", "open", "ended" };
enum EndOfStreamError { "network", "decode" };
