[Exposed=Window, LegacyUnenumerableNamedProperties]
interface SourceBufferList : EventTarget {
    readonly attribute unsigned long length;
    getter SourceBuffer (unsigned long index);
    attribute EventHandler onaddsourcebuffer;
    attribute EventHandler onremovesourcebuffer;
};
