#import <DOM/EventHandler.idl>
#import <DOM/EventTarget.idl>
#import <MediaSourceExtensions/SourceBuffer.idl>

[Exposed=(Window,DedicatedWorker)]
interface SourceBufferList : EventTarget {
    readonly attribute unsigned long length;
    getter SourceBuffer (unsigned long index);
    attribute EventHandler onaddsourcebuffer;
    attribute EventHandler onremovesourcebuffer;
};
